### ISSUE TITLE
xlnet版本

### ISSUE THREAD

**Issue by jianminli55** [JinghaoZ/XLNet-multilabel#1]
作者好，请问一下是用了哪个版本的xlnet呢？

**Comment by zhangqing-yuguo** [comment]
请问一下您是怎么加的评价指标的，感谢！

**Comment by jinghao2eebd** [comment]
> 作者好，请问一下是用了哪个版本的xlnet呢？



原文用的xlnet-base-cased, 中文的话换成对应的中文pytorch版本就可以了
