### ISSUE TITLE
评价指标

### ISSUE THREAD

**Issue by zhangqing-yuguo** [JinghaoZ/XLNet-multilabel#2]
作者您好！我想实现的您的代码来学习，想增加评价指标，如acc，pre，recall，以及宏观微观f1值，不知道如何添加，希望作者指教，万分感谢！

**Comment by jinghao2eebd** [comment]
> 作者您好！我想实现的您的代码来学习，想增加评价指标，如acc，pre，recall，以及宏观微观f1值，不知道如何添加，希望作者指教，万分感谢！

抱歉过了这么久才回复
可以使用sklearn的multilabel_confusion_matrix, 也可以用f1-score, sklearn的多标签f1-score和单标签有略微不同
